#!/bin/sh

if [[ ! -f $(dirname "$0")/"../../rebase-merge" ]]; then
    echo "Taking a snapshot..."
    ffmpeg \
        -ss 00:00:00 \
        -f avfoundation \
        -r 30 \
        -i "0" \
        -t 1 \
        -frames:v 1 \
        -q:v 2 \
        -hide_banner -loglevel panic \
        ~/.gitshots/$(date -Iseconds).jpg
fi