#!/bin/sh

### lolcommits hook (begin) ###
LANG="en_US" && PATH="$PATH:/Users/nbdeg/.rvm/rubies/ruby-2.4.4/bin:/usr/local/bin" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --capture ; fi
###  lolcommits hook (end)  ###
