tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "asciinema"
brew "cowsay"
brew "fortune"
brew "httpie"
brew "imagemagick"
brew "imagesnap"
brew "lolcat"
brew "mas"
brew "n"
brew "pipenv"
brew "pyenv"
brew "speedtest-cli"
brew "thefuck"
brew "watchman"
brew "yarn", args: ["without-node"]
brew "zsh"
cask "1password"
cask "1password-cli"
cask "basictex"
cask "discord"
cask "docker"
cask "font-hack"
cask "font-source-sans-pro"
cask "gitify"
cask "gitkraken"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "jetbrains-toolbox"
cask "marshallofsound-google-play-music-player"
cask "sketch"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "com.apple.dt.Xcode", id: 497799835
mas "com.crowdcafe.windowmagnet", id: 441258766
mas "com.gingerlabs.NotabilityMac", id: 736189492
mas "com.if.Amphetamine", id: 937984704
mas "com.microsoft.Excel", id: 462058435
mas "com.microsoft.Word", id: 462054704
