tap "bufbuild/buf"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mike-engel/jwt-cli"
tap "warrensbox/tap"
brew "awscli"
brew "bazel"
brew "ccat"
brew "coreutils"
brew "cowsay"
brew "ffmpeg"
brew "figlet"
brew "fish"
brew "fortune"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "gitmoji"
brew "go"
brew "graphviz"
brew "htop"
brew "httpie"
brew "python@3.8"
brew "imagemagick"
brew "lolcat"
brew "mas"
brew "n"
brew "postgresql"
brew "pre-commit"
brew "protobuf"
brew "pyenv"
brew "ruby"
brew "thefuck"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "bufbuild/buf/buf"
brew "mike-engel/jwt-cli/jwt-cli"
brew "warrensbox/tap/tfswitch"
cask "1password"
cask "anki"
cask "balenaetcher"
cask "dash"
cask "discord"
cask "docker"
cask "figma"
cask "font-jetbrains-mono"
cask "font-source-sans-pro"
cask "gitify"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "java"
cask "jetbrains-toolbox"
cask "mactex-no-gui"
cask "ngrok"
cask "notion"
cask "postman"
cask "spotify"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Magnet", id: 441258766
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Notability", id: 736189492
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
